name: XPBottle
api: 2.0.0
main: Muqsit\XPBottle
version: 1.0
commands:
  xpbottle:
    description: Redeem XP into XP Bottles.
  exp:
    description: Check your current experience.
permission:
  redeem.exp:
    default: true
